version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false
    steps:
      - checkout
      - run: sudo apt update && sudo apt install -y libpq-dev
      - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uv python install
      - run: uv venv
      - run: uv pip install -r requirements.txt
      - run: uv pip install coveralls
      - run: mkdir -p media/humppa-music
      - run: docker run -d -v media:/data -p 9000:9000 minio/minio:edge server /data
      - run:
          name: Run tests
          command: |
            coverage run --source=nickelodeon manage.py test --settings=nickelodeon.site.test_settings
      - run:
          name: Upload coverage
          command: python -m coveralls

workflows:
  main:
    jobs:
      - build-and-test
